2025-08-28 14:59:48,901	INFO monitor.py:726 -- Starting monitor using ray installation: C:\Users\luoji12103\AppData\Roaming\Python\Python312\site-packages\ray\__init__.py
2025-08-28 14:59:48,901	INFO monitor.py:727 -- Ray version: 2.48.0
2025-08-28 14:59:48,901	INFO monitor.py:728 -- Ray commit: 03491225d59a1ffde99c3628969ccf456be13efd
2025-08-28 14:59:48,901	INFO monitor.py:729 -- Monitor started with command: ['C:\\Users\\luoji12103\\AppData\\Roaming\\Python\\Python312\\site-packages\\ray\\autoscaler\\_private\\monitor.py', '--logs-dir=D:\\MyUser\\HKUSTGZ\\DOIT\\6G Program\\CastRay\\ray_temp\\session_2025-08-28_14-59-46_392482_100648\\logs', '--logging-rotate-bytes=536870912', '--logging-rotate-backup-count=5', '--gcs-address=127.0.0.1:65416', '--stdout-filepath=D:\\MyUser\\HKUSTGZ\\DOIT\\6G Program\\CastRay\\ray_temp\\session_2025-08-28_14-59-46_392482_100648\\logs\\monitor.out', '--stderr-filepath=D:\\MyUser\\HKUSTGZ\\DOIT\\6G Program\\CastRay\\ray_temp\\session_2025-08-28_14-59-46_392482_100648\\logs\\monitor.err', '--monitor-ip=127.0.0.1']
2025-08-28 14:59:48,904	INFO monitor.py:161 -- session_name: session_2025-08-28_14-59-46_392482_100648
2025-08-28 14:59:48,905	WARNING monitor.py:214 -- `prometheus_client` not found, so metrics will not be exported.
2025-08-28 14:59:48,905	INFO monitor.py:218 -- Monitor: Started
2025-08-28 14:59:48,910	INFO autoscaler.py:280 -- disable_node_updaters:False
2025-08-28 14:59:48,910	INFO autoscaler.py:289 -- disable_launch_config_check:True
2025-08-28 14:59:48,910	INFO autoscaler.py:301 -- foreground_node_launch:False
2025-08-28 14:59:48,910	INFO autoscaler.py:311 -- worker_liveness_check:True
2025-08-28 14:59:48,911	INFO autoscaler.py:361 -- StandardAutoscaler: {'cluster_name': 'default', 'max_workers': 0, 'upscaling_speed': 1.0, 'docker': {}, 'idle_timeout_minutes': 0, 'provider': {'type': 'readonly', 'use_node_id_as_ip': True, 'disable_launch_config_check': True}, 'auth': {}, 'available_node_types': {'ray.head.default': {'resources': {}, 'node_config': {}, 'max_workers': 0}}, 'head_node_type': 'ray.head.default', 'file_mounts': {}, 'cluster_synced_files': [], 'file_mounts_sync_continuously': False, 'rsync_exclude': [], 'rsync_filter': [], 'initialization_commands': [], 'setup_commands': [], 'head_setup_commands': [], 'worker_setup_commands': [], 'head_start_ray_commands': [], 'worker_start_ray_commands': []}
2025-08-28 14:59:48,912	INFO monitor.py:404 -- Autoscaler has not yet received load metrics. Waiting.
